[<AutoOpen>]
module Browser.DomExtensions

open Fable.Core
open Browser.Types

type Document with
    [<Emit("$0.addEventListener('abort',$1...)")>] member __.addEventListener_abort(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('activate',$1...)")>] member __.addEventListener_activate(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('beforeactivate',$1...)")>] member __.addEventListener_beforeactivate(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('beforedeactivate',$1...)")>] member __.addEventListener_beforedeactivate(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('blur',$1...)")>] member __.addEventListener_blur(listener: (FocusEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('canplay',$1...)")>] member __.addEventListener_canplay(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('canplaythrough',$1...)")>] member __.addEventListener_canplaythrough(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('change',$1...)")>] member __.addEventListener_change(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('click',$1...)")>] member __.addEventListener_click(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('contextmenu',$1...)")>] member __.addEventListener_contextmenu(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('dblclick',$1...)")>] member __.addEventListener_dblclick(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('deactivate',$1...)")>] member __.addEventListener_deactivate(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('drag',$1...)")>] member __.addEventListener_drag(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('dragend',$1...)")>] member __.addEventListener_dragend(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('dragenter',$1...)")>] member __.addEventListener_dragenter(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('dragleave',$1...)")>] member __.addEventListener_dragleave(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('dragover',$1...)")>] member __.addEventListener_dragover(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('dragstart',$1...)")>] member __.addEventListener_dragstart(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('drop',$1...)")>] member __.addEventListener_drop(listener: (DragEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('durationchange',$1...)")>] member __.addEventListener_durationchange(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('emptied',$1...)")>] member __.addEventListener_emptied(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('ended',$1...)")>] member __.addEventListener_ended(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('error',$1...)")>] member __.addEventListener_error(listener: (ErrorEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('focus',$1...)")>] member __.addEventListener_focus(listener: (FocusEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('fullscreenchange',$1...)")>] member __.addEventListener_fullscreenchange(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('fullscreenerror',$1...)")>] member __.addEventListener_fullscreenerror(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('input',$1...)")>] member __.addEventListener_input(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('keydown',$1...)")>] member __.addEventListener_keydown(listener: (KeyboardEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('keypress',$1...)")>] member __.addEventListener_keypress(listener: (KeyboardEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('keyup',$1...)")>] member __.addEventListener_keyup(listener: (KeyboardEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('load',$1...)")>] member __.addEventListener_load(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('loadeddata',$1...)")>] member __.addEventListener_loadeddata(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('loadedmetadata',$1...)")>] member __.addEventListener_loadedmetadata(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('loadstart',$1...)")>] member __.addEventListener_loadstart(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('mousedown',$1...)")>] member __.addEventListener_mousedown(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('mousemove',$1...)")>] member __.addEventListener_mousemove(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('mouseout',$1...)")>] member __.addEventListener_mouseout(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('mouseover',$1...)")>] member __.addEventListener_mouseover(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('mouseup',$1...)")>] member __.addEventListener_mouseup(listener: (MouseEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('mousewheel',$1...)")>] member __.addEventListener_mousewheel(listener: (MouseWheelEvent -> unit), ?useCapture: bool): unit = jsNative
    // [<Emit("$0.addEventListener('mssitemodejumplistitemremoved',$1...)")>] member __.addEventListener_mssitemodejumplistitemremoved(listener: (MSSiteModeEvent -> unit), ?useCapture: bool): unit = jsNative
    // [<Emit("$0.addEventListener('msthumbnailclick',$1...)")>] member __.addEventListener_msthumbnailclick(listener: (MSSiteModeEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pause',$1...)")>] member __.addEventListener_pause(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('play',$1...)")>] member __.addEventListener_play(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('playing',$1...)")>] member __.addEventListener_playing(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointercancel',$1...)")>] member __.addEventListener_pointercancel(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerdown',$1...)")>] member __.addEventListener_pointerdown(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerenter',$1...)")>] member __.addEventListener_pointerenter(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerleave',$1...)")>] member __.addEventListener_pointerleave(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerlockchange',$1...)")>] member __.addEventListener_pointerlockchange(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerlockerror',$1...)")>] member __.addEventListener_pointerlockerror(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointermove',$1...)")>] member __.addEventListener_pointermove(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerout',$1...)")>] member __.addEventListener_pointerout(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerover',$1...)")>] member __.addEventListener_pointerover(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('pointerup',$1...)")>] member __.addEventListener_pointerup(listener: (PointerEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('progress',$1...)")>] member __.addEventListener_progress(listener: (ProgressEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('ratechange',$1...)")>] member __.addEventListener_ratechange(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('readystatechange',$1...)")>] member __.addEventListener_readystatechange(listener: (ProgressEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('reset',$1...)")>] member __.addEventListener_reset(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('scroll',$1...)")>] member __.addEventListener_scroll(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('seeked',$1...)")>] member __.addEventListener_seeked(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('seeking',$1...)")>] member __.addEventListener_seeking(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('select',$1...)")>] member __.addEventListener_select(listener: (UIEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('selectstart',$1...)")>] member __.addEventListener_selectstart(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('stalled',$1...)")>] member __.addEventListener_stalled(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('stop',$1...)")>] member __.addEventListener_stop(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('submit',$1...)")>] member __.addEventListener_submit(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('suspend',$1...)")>] member __.addEventListener_suspend(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('timeupdate',$1...)")>] member __.addEventListener_timeupdate(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('touchcancel',$1...)")>] member __.addEventListener_touchcancel(listener: (TouchEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('touchend',$1...)")>] member __.addEventListener_touchend(listener: (TouchEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('touchmove',$1...)")>] member __.addEventListener_touchmove(listener: (TouchEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('touchstart',$1...)")>] member __.addEventListener_touchstart(listener: (TouchEvent -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('volumechange',$1...)")>] member __.addEventListener_volumechange(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('waiting',$1...)")>] member __.addEventListener_waiting(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('webkitfullscreenchange',$1...)")>] member __.addEventListener_webkitfullscreenchange(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('webkitfullscreenerror',$1...)")>] member __.addEventListener_webkitfullscreenerror(listener: (Event -> unit), ?useCapture: bool): unit = jsNative
    [<Emit("$0.addEventListener('wheel',$1...)")>] member __.addEventListener_wheel(listener: (WheelEvent -> unit), ?useCapture: bool): unit = jsNative

    [<Emit("$0.createElement('a')")>] member __.createElement_a(): HTMLAnchorElement = jsNative
    [<Emit("$0.createElement('abbr')")>] member __.createElement_abbr(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('acronym')")>] member __.createElement_acronym(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('address')")>] member __.createElement_address(): HTMLBlockElement = jsNative
    // [<Emit("$0.createElement('applet')")>] member __.createElement_applet(): HTMLAppletElement = jsNative
    [<Emit("$0.createElement('area')")>] member __.createElement_area(): HTMLAreaElement = jsNative
    [<Emit("$0.createElement('audio')")>] member __.createElement_audio(): HTMLAudioElement = jsNative
    [<Emit("$0.createElement('b')")>] member __.createElement_b(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('base')")>] member __.createElement_base(): HTMLBaseElement = jsNative
    // [<Emit("$0.createElement('basefont')")>] member __.createElement_basefont(): HTMLBaseFontElement = jsNative
    [<Emit("$0.createElement('bdo')")>] member __.createElement_bdo(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('big')")>] member __.createElement_big(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('blockquote')")>] member __.createElement_blockquote(): HTMLBlockElement = jsNative
    [<Emit("$0.createElement('body')")>] member __.createElement_body(): HTMLBodyElement = jsNative
    [<Emit("$0.createElement('br')")>] member __.createElement_br(): HTMLBRElement = jsNative
    [<Emit("$0.createElement('button')")>] member __.createElement_button(): HTMLButtonElement = jsNative
    [<Emit("$0.createElement('canvas')")>] member __.createElement_canvas(): HTMLCanvasElement = jsNative
    [<Emit("$0.createElement('caption')")>] member __.createElement_caption(): HTMLTableCaptionElement = jsNative
    [<Emit("$0.createElement('center')")>] member __.createElement_center(): HTMLBlockElement = jsNative
    [<Emit("$0.createElement('cite')")>] member __.createElement_cite(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('code')")>] member __.createElement_code(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('col')")>] member __.createElement_col(): HTMLTableColElement = jsNative
    [<Emit("$0.createElement('colgroup')")>] member __.createElement_colgroup(): HTMLTableColElement = jsNative
    [<Emit("$0.createElement('datalist')")>] member __.createElement_datalist(): HTMLDataListElement = jsNative
    [<Emit("$0.createElement('dd')")>] member __.createElement_dd(): HTMLDDElement = jsNative
    [<Emit("$0.createElement('del')")>] member __.createElement_del(): HTMLModElement = jsNative
    [<Emit("$0.createElement('dfn')")>] member __.createElement_dfn(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('dir')")>] member __.createElement_dir(): HTMLDirectoryElement = jsNative
    [<Emit("$0.createElement('div')")>] member __.createElement_div(): HTMLDivElement = jsNative
    [<Emit("$0.createElement('dl')")>] member __.createElement_dl(): HTMLDListElement = jsNative
    [<Emit("$0.createElement('dt')")>] member __.createElement_dt(): HTMLDTElement = jsNative
    [<Emit("$0.createElement('em')")>] member __.createElement_em(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('embed')")>] member __.createElement_embed(): HTMLEmbedElement = jsNative
    [<Emit("$0.createElement('fieldset')")>] member __.createElement_fieldset(): HTMLFieldSetElement = jsNative
    [<Emit("$0.createElement('font')")>] member __.createElement_font(): HTMLFontElement = jsNative
    [<Emit("$0.createElement('form')")>] member __.createElement_form(): HTMLFormElement = jsNative
    [<Emit("$0.createElement('frame')")>] member __.createElement_frame(): HTMLFrameElement = jsNative
    // [<Emit("$0.createElement('frameset')")>] member __.createElement_frameset(): HTMLFrameSetElement = jsNative
    [<Emit("$0.createElement('h1')")>] member __.createElement_h1(): HTMLHeadingElement = jsNative
    [<Emit("$0.createElement('h2')")>] member __.createElement_h2(): HTMLHeadingElement = jsNative
    [<Emit("$0.createElement('h3')")>] member __.createElement_h3(): HTMLHeadingElement = jsNative
    [<Emit("$0.createElement('h4')")>] member __.createElement_h4(): HTMLHeadingElement = jsNative
    [<Emit("$0.createElement('h5')")>] member __.createElement_h5(): HTMLHeadingElement = jsNative
    [<Emit("$0.createElement('h6')")>] member __.createElement_h6(): HTMLHeadingElement = jsNative
    [<Emit("$0.createElement('head')")>] member __.createElement_head(): HTMLHeadElement = jsNative
    [<Emit("$0.createElement('hr')")>] member __.createElement_hr(): HTMLHRElement = jsNative
    [<Emit("$0.createElement('html')")>] member __.createElement_html(): HTMLHtmlElement = jsNative
    [<Emit("$0.createElement('i')")>] member __.createElement_i(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('iframe')")>] member __.createElement_iframe(): HTMLIFrameElement = jsNative
    [<Emit("$0.createElement('img')")>] member __.createElement_img(): HTMLImageElement = jsNative
    [<Emit("$0.createElement('input')")>] member __.createElement_input(): HTMLInputElement = jsNative
    [<Emit("$0.createElement('ins')")>] member __.createElement_ins(): HTMLModElement = jsNative
    // [<Emit("$0.createElement('isindex')")>] member __.createElement_isindex(): HTMLIsIndexElement = jsNative
    [<Emit("$0.createElement('kbd')")>] member __.createElement_kbd(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('keygen')")>] member __.createElement_keygen(): HTMLBlockElement = jsNative
    [<Emit("$0.createElement('label')")>] member __.createElement_label(): HTMLLabelElement = jsNative
    [<Emit("$0.createElement('legend')")>] member __.createElement_legend(): HTMLLegendElement = jsNative
    [<Emit("$0.createElement('li')")>] member __.createElement_li(): HTMLLIElement = jsNative
    [<Emit("$0.createElement('link')")>] member __.createElement_link(): HTMLLinkElement = jsNative
    [<Emit("$0.createElement('listing')")>] member __.createElement_listing(): HTMLBlockElement = jsNative
    [<Emit("$0.createElement('map')")>] member __.createElement_map(): HTMLMapElement = jsNative
    // [<Emit("$0.createElement('marquee')")>] member __.createElement_marquee(): HTMLMarqueeElement = jsNative
    [<Emit("$0.createElement('menu')")>] member __.createElement_menu(): HTMLMenuElement = jsNative
    [<Emit("$0.createElement('meta')")>] member __.createElement_meta(): HTMLMetaElement = jsNative
    [<Emit("$0.createElement('nextid')")>] member __.createElement_nextid(): HTMLNextIdElement = jsNative
    [<Emit("$0.createElement('nobr')")>] member __.createElement_nobr(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('object')")>] member __.createElement_object(): HTMLObjectElement = jsNative
    [<Emit("$0.createElement('ol')")>] member __.createElement_ol(): HTMLOListElement = jsNative
    [<Emit("$0.createElement('optgroup')")>] member __.createElement_optgroup(): HTMLOptGroupElement = jsNative
    [<Emit("$0.createElement('option')")>] member __.createElement_option(): HTMLOptionElement = jsNative
    [<Emit("$0.createElement('p')")>] member __.createElement_p(): HTMLParagraphElement = jsNative
    [<Emit("$0.createElement('param')")>] member __.createElement_param(): HTMLParamElement = jsNative
    [<Emit("$0.createElement('plaintext')")>] member __.createElement_plaintext(): HTMLBlockElement = jsNative
    [<Emit("$0.createElement('pre')")>] member __.createElement_pre(): HTMLPreElement = jsNative
    [<Emit("$0.createElement('progress')")>] member __.createElement_progress(): HTMLProgressElement = jsNative
    [<Emit("$0.createElement('q')")>] member __.createElement_q(): HTMLQuoteElement = jsNative
    [<Emit("$0.createElement('rt')")>] member __.createElement_rt(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('ruby')")>] member __.createElement_ruby(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('s')")>] member __.createElement_s(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('samp')")>] member __.createElement_samp(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('script')")>] member __.createElement_script(): HTMLScriptElement = jsNative
    [<Emit("$0.createElement('select')")>] member __.createElement_select(): HTMLSelectElement = jsNative
    [<Emit("$0.createElement('small')")>] member __.createElement_small(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('source')")>] member __.createElement_source(): HTMLSourceElement = jsNative
    [<Emit("$0.createElement('span')")>] member __.createElement_span(): HTMLSpanElement = jsNative
    [<Emit("$0.createElement('strike')")>] member __.createElement_strike(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('strong')")>] member __.createElement_strong(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('style')")>] member __.createElement_style(): HTMLStyleElement = jsNative
    [<Emit("$0.createElement('sub')")>] member __.createElement_sub(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('sup')")>] member __.createElement_sup(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('table')")>] member __.createElement_table(): HTMLTableElement = jsNative
    [<Emit("$0.createElement('tbody')")>] member __.createElement_tbody(): HTMLTableSectionElement = jsNative
    [<Emit("$0.createElement('td')")>] member __.createElement_td(): HTMLTableDataCellElement = jsNative
    [<Emit("$0.createElement('textarea')")>] member __.createElement_textarea(): HTMLTextAreaElement = jsNative
    [<Emit("$0.createElement('tfoot')")>] member __.createElement_tfoot(): HTMLTableSectionElement = jsNative
    [<Emit("$0.createElement('th')")>] member __.createElement_th(): HTMLTableHeaderCellElement = jsNative
    [<Emit("$0.createElement('thead')")>] member __.createElement_thead(): HTMLTableSectionElement = jsNative
    [<Emit("$0.createElement('title')")>] member __.createElement_title(): HTMLTitleElement = jsNative
    [<Emit("$0.createElement('tr')")>] member __.createElement_tr(): HTMLTableRowElement = jsNative
    [<Emit("$0.createElement('track')")>] member __.createElement_track(): HTMLTrackElement = jsNative
    [<Emit("$0.createElement('tt')")>] member __.createElement_tt(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('u')")>] member __.createElement_u(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('ul')")>] member __.createElement_ul(): HTMLUListElement = jsNative
    [<Emit("$0.createElement('var')")>] member __.createElement_var(): HTMLPhraseElement = jsNative
    [<Emit("$0.createElement('video')")>] member __.createElement_video(): HTMLVideoElement = jsNative
    // [<Emit("$0.createElement('x-ms-webview')")>] member __.``():``: unit -> MSHTMLWebViewElement = jsNative
    [<Emit("$0.createElement('xmp')")>] member __.createElement_xmp(): HTMLBlockElement = jsNative

    [<Emit("$0.getElementsByTagName('a')")>] member __.getElementsByTagName_a(): NodeListOf<HTMLAnchorElement> = jsNative
    [<Emit("$0.getElementsByTagName('abbr')")>] member __.getElementsByTagName_abbr(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('acronym')")>] member __.getElementsByTagName_acronym(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('address')")>] member __.getElementsByTagName_address(): NodeListOf<HTMLBlockElement> = jsNative
    // [<Emit("$0.getElementsByTagName('applet')")>] member __.getElementsByTagName_applet(): NodeListOf<HTMLAppletElement> = jsNative
    [<Emit("$0.getElementsByTagName('area')")>] member __.getElementsByTagName_area(): NodeListOf<HTMLAreaElement> = jsNative
    [<Emit("$0.getElementsByTagName('article')")>] member __.getElementsByTagName_article(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('aside')")>] member __.getElementsByTagName_aside(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('audio')")>] member __.getElementsByTagName_audio(): NodeListOf<HTMLAudioElement> = jsNative
    [<Emit("$0.getElementsByTagName('b')")>] member __.getElementsByTagName_b(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('base')")>] member __.getElementsByTagName_base(): NodeListOf<HTMLBaseElement> = jsNative
    // [<Emit("$0.getElementsByTagName('basefont')")>] member __.getElementsByTagName_basefont(): NodeListOf<HTMLBaseFontElement> = jsNative
    [<Emit("$0.getElementsByTagName('bdo')")>] member __.getElementsByTagName_bdo(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('big')")>] member __.getElementsByTagName_big(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('blockquote')")>] member __.getElementsByTagName_blockquote(): NodeListOf<HTMLBlockElement> = jsNative
    [<Emit("$0.getElementsByTagName('body')")>] member __.getElementsByTagName_body(): NodeListOf<HTMLBodyElement> = jsNative
    [<Emit("$0.getElementsByTagName('br')")>] member __.getElementsByTagName_br(): NodeListOf<HTMLBRElement> = jsNative
    [<Emit("$0.getElementsByTagName('button')")>] member __.getElementsByTagName_button(): NodeListOf<HTMLButtonElement> = jsNative
    [<Emit("$0.getElementsByTagName('canvas')")>] member __.getElementsByTagName_canvas(): NodeListOf<HTMLCanvasElement> = jsNative
    [<Emit("$0.getElementsByTagName('caption')")>] member __.getElementsByTagName_caption(): NodeListOf<HTMLTableCaptionElement> = jsNative
    [<Emit("$0.getElementsByTagName('center')")>] member __.getElementsByTagName_center(): NodeListOf<HTMLBlockElement> = jsNative
    // [<Emit("$0.getElementsByTagName('circle')")>] member __.getElementsByTagName_circle(): NodeListOf<SVGCircleElement> = jsNative
    [<Emit("$0.getElementsByTagName('cite')")>] member __.getElementsByTagName_cite(): NodeListOf<HTMLPhraseElement> = jsNative
    // [<Emit("$0.getElementsByTagName('clippath')")>] member __.getElementsByTagName_clippath(): NodeListOf<SVGClipPathElement> = jsNative
    [<Emit("$0.getElementsByTagName('code')")>] member __.getElementsByTagName_code(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('col')")>] member __.getElementsByTagName_col(): NodeListOf<HTMLTableColElement> = jsNative
    [<Emit("$0.getElementsByTagName('colgroup')")>] member __.getElementsByTagName_colgroup(): NodeListOf<HTMLTableColElement> = jsNative
    [<Emit("$0.getElementsByTagName('datalist')")>] member __.getElementsByTagName_datalist(): NodeListOf<HTMLDataListElement> = jsNative
    [<Emit("$0.getElementsByTagName('dd')")>] member __.getElementsByTagName_dd(): NodeListOf<HTMLDDElement> = jsNative
    // [<Emit("$0.getElementsByTagName('defs')")>] member __.getElementsByTagName_defs(): NodeListOf<SVGDefsElement> = jsNative
    [<Emit("$0.getElementsByTagName('del')")>] member __.getElementsByTagName_del(): NodeListOf<HTMLModElement> = jsNative
    // [<Emit("$0.getElementsByTagName('desc')")>] member __.getElementsByTagName_desc(): NodeListOf<SVGDescElement> = jsNative
    [<Emit("$0.getElementsByTagName('dfn')")>] member __.getElementsByTagName_dfn(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('dir')")>] member __.getElementsByTagName_dir(): NodeListOf<HTMLDirectoryElement> = jsNative
    [<Emit("$0.getElementsByTagName('div')")>] member __.getElementsByTagName_div(): NodeListOf<HTMLDivElement> = jsNative
    [<Emit("$0.getElementsByTagName('dl')")>] member __.getElementsByTagName_dl(): NodeListOf<HTMLDListElement> = jsNative
    [<Emit("$0.getElementsByTagName('dt')")>] member __.getElementsByTagName_dt(): NodeListOf<HTMLDTElement> = jsNative
    // [<Emit("$0.getElementsByTagName('ellipse')")>] member __.getElementsByTagName_ellipse(): NodeListOf<SVGEllipseElement> = jsNative
    [<Emit("$0.getElementsByTagName('em')")>] member __.getElementsByTagName_em(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('embed')")>] member __.getElementsByTagName_embed(): NodeListOf<HTMLEmbedElement> = jsNative
    // [<Emit("$0.getElementsByTagName('feblend')")>] member __.getElementsByTagName_feblend(): NodeListOf<SVGFEBlendElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fecolormatrix')")>] member __.getElementsByTagName_fecolormatrix(): NodeListOf<SVGFEColorMatrixElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fecomponenttransfer')")>] member __.getElementsByTagName_fecomponenttransfer(): NodeListOf<SVGFEComponentTransferElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fecomposite')")>] member __.getElementsByTagName_fecomposite(): NodeListOf<SVGFECompositeElement> = jsNative
    // [<Emit("$0.getElementsByTagName('feconvolvematrix')")>] member __.getElementsByTagName_feconvolvematrix(): NodeListOf<SVGFEConvolveMatrixElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fediffuselighting')")>] member __.getElementsByTagName_fediffuselighting(): NodeListOf<SVGFEDiffuseLightingElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fedisplacementmap')")>] member __.getElementsByTagName_fedisplacementmap(): NodeListOf<SVGFEDisplacementMapElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fedistantlight')")>] member __.getElementsByTagName_fedistantlight(): NodeListOf<SVGFEDistantLightElement> = jsNative
    // [<Emit("$0.getElementsByTagName('feflood')")>] member __.getElementsByTagName_feflood(): NodeListOf<SVGFEFloodElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fefunca')")>] member __.getElementsByTagName_fefunca(): NodeListOf<SVGFEFuncAElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fefuncb')")>] member __.getElementsByTagName_fefuncb(): NodeListOf<SVGFEFuncBElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fefuncg')")>] member __.getElementsByTagName_fefuncg(): NodeListOf<SVGFEFuncGElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fefuncr')")>] member __.getElementsByTagName_fefuncr(): NodeListOf<SVGFEFuncRElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fegaussianblur')")>] member __.getElementsByTagName_fegaussianblur(): NodeListOf<SVGFEGaussianBlurElement> = jsNative
    // [<Emit("$0.getElementsByTagName('feimage')")>] member __.getElementsByTagName_feimage(): NodeListOf<SVGFEImageElement> = jsNative
    // [<Emit("$0.getElementsByTagName('femerge')")>] member __.getElementsByTagName_femerge(): NodeListOf<SVGFEMergeElement> = jsNative
    // [<Emit("$0.getElementsByTagName('femergenode')")>] member __.getElementsByTagName_femergenode(): NodeListOf<SVGFEMergeNodeElement> = jsNative
    // [<Emit("$0.getElementsByTagName('femorphology')")>] member __.getElementsByTagName_femorphology(): NodeListOf<SVGFEMorphologyElement> = jsNative
    // [<Emit("$0.getElementsByTagName('feoffset')")>] member __.getElementsByTagName_feoffset(): NodeListOf<SVGFEOffsetElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fepointlight')")>] member __.getElementsByTagName_fepointlight(): NodeListOf<SVGFEPointLightElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fespecularlighting')")>] member __.getElementsByTagName_fespecularlighting(): NodeListOf<SVGFESpecularLightingElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fespotlight')")>] member __.getElementsByTagName_fespotlight(): NodeListOf<SVGFESpotLightElement> = jsNative
    // [<Emit("$0.getElementsByTagName('fetile')")>] member __.getElementsByTagName_fetile(): NodeListOf<SVGFETileElement> = jsNative
    // [<Emit("$0.getElementsByTagName('feturbulence')")>] member __.getElementsByTagName_feturbulence(): NodeListOf<SVGFETurbulenceElement> = jsNative
    [<Emit("$0.getElementsByTagName('fieldset')")>] member __.getElementsByTagName_fieldset(): NodeListOf<HTMLFieldSetElement> = jsNative
    [<Emit("$0.getElementsByTagName('figcaption')")>] member __.getElementsByTagName_figcaption(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('figure')")>] member __.getElementsByTagName_figure(): NodeListOf<HTMLElement> = jsNative
    // [<Emit("$0.getElementsByTagName('filter')")>] member __.getElementsByTagName_filter(): NodeListOf<SVGFilterElement> = jsNative
    [<Emit("$0.getElementsByTagName('font')")>] member __.getElementsByTagName_font(): NodeListOf<HTMLFontElement> = jsNative
    [<Emit("$0.getElementsByTagName('footer')")>] member __.getElementsByTagName_footer(): NodeListOf<HTMLElement> = jsNative
    // [<Emit("$0.getElementsByTagName('foreignobject')")>] member __.getElementsByTagName_foreignobject(): NodeListOf<SVGForeignObjectElement> = jsNative
    [<Emit("$0.getElementsByTagName('form')")>] member __.getElementsByTagName_form(): NodeListOf<HTMLFormElement> = jsNative
    [<Emit("$0.getElementsByTagName('frame')")>] member __.getElementsByTagName_frame(): NodeListOf<HTMLFrameElement> = jsNative
    // [<Emit("$0.getElementsByTagName('frameset')")>] member __.getElementsByTagName_frameset(): NodeListOf<HTMLFrameSetElement> = jsNative
    // [<Emit("$0.getElementsByTagName('g')")>] member __.getElementsByTagName_g(): NodeListOf<SVGGElement> = jsNative
    [<Emit("$0.getElementsByTagName('h1')")>] member __.getElementsByTagName_h1(): NodeListOf<HTMLHeadingElement> = jsNative
    [<Emit("$0.getElementsByTagName('h2')")>] member __.getElementsByTagName_h2(): NodeListOf<HTMLHeadingElement> = jsNative
    [<Emit("$0.getElementsByTagName('h3')")>] member __.getElementsByTagName_h3(): NodeListOf<HTMLHeadingElement> = jsNative
    [<Emit("$0.getElementsByTagName('h4')")>] member __.getElementsByTagName_h4(): NodeListOf<HTMLHeadingElement> = jsNative
    [<Emit("$0.getElementsByTagName('h5')")>] member __.getElementsByTagName_h5(): NodeListOf<HTMLHeadingElement> = jsNative
    [<Emit("$0.getElementsByTagName('h6')")>] member __.getElementsByTagName_h6(): NodeListOf<HTMLHeadingElement> = jsNative
    [<Emit("$0.getElementsByTagName('head')")>] member __.getElementsByTagName_head(): NodeListOf<HTMLHeadElement> = jsNative
    [<Emit("$0.getElementsByTagName('header')")>] member __.getElementsByTagName_header(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('hgroup')")>] member __.getElementsByTagName_hgroup(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('hr')")>] member __.getElementsByTagName_hr(): NodeListOf<HTMLHRElement> = jsNative
    [<Emit("$0.getElementsByTagName('html')")>] member __.getElementsByTagName_html(): NodeListOf<HTMLHtmlElement> = jsNative
    [<Emit("$0.getElementsByTagName('i')")>] member __.getElementsByTagName_i(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('iframe')")>] member __.getElementsByTagName_iframe(): NodeListOf<HTMLIFrameElement> = jsNative
    // [<Emit("$0.getElementsByTagName('image')")>] member __.getElementsByTagName_image(): NodeListOf<SVGImageElement> = jsNative
    [<Emit("$0.getElementsByTagName('img')")>] member __.getElementsByTagName_img(): NodeListOf<HTMLImageElement> = jsNative
    [<Emit("$0.getElementsByTagName('input')")>] member __.getElementsByTagName_input(): NodeListOf<HTMLInputElement> = jsNative
    [<Emit("$0.getElementsByTagName('ins')")>] member __.getElementsByTagName_ins(): NodeListOf<HTMLModElement> = jsNative
    // [<Emit("$0.getElementsByTagName('isindex')")>] member __.getElementsByTagName_isindex(): NodeListOf<HTMLIsIndexElement> = jsNative
    [<Emit("$0.getElementsByTagName('kbd')")>] member __.getElementsByTagName_kbd(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('keygen')")>] member __.getElementsByTagName_keygen(): NodeListOf<HTMLBlockElement> = jsNative
    [<Emit("$0.getElementsByTagName('label')")>] member __.getElementsByTagName_label(): NodeListOf<HTMLLabelElement> = jsNative
    [<Emit("$0.getElementsByTagName('legend')")>] member __.getElementsByTagName_legend(): NodeListOf<HTMLLegendElement> = jsNative
    [<Emit("$0.getElementsByTagName('li')")>] member __.getElementsByTagName_li(): NodeListOf<HTMLLIElement> = jsNative
    // [<Emit("$0.getElementsByTagName('line')")>] member __.getElementsByTagName_line(): NodeListOf<SVGLineElement> = jsNative
    // [<Emit("$0.getElementsByTagName('lineargradient')")>] member __.getElementsByTagName_lineargradient(): NodeListOf<SVGLinearGradientElement> = jsNative
    [<Emit("$0.getElementsByTagName('link')")>] member __.getElementsByTagName_link(): NodeListOf<HTMLLinkElement> = jsNative
    [<Emit("$0.getElementsByTagName('listing')")>] member __.getElementsByTagName_listing(): NodeListOf<HTMLBlockElement> = jsNative
    [<Emit("$0.getElementsByTagName('map')")>] member __.getElementsByTagName_map(): NodeListOf<HTMLMapElement> = jsNative
    [<Emit("$0.getElementsByTagName('mark')")>] member __.getElementsByTagName_mark(): NodeListOf<HTMLElement> = jsNative
    // [<Emit("$0.getElementsByTagName('marker')")>] member __.getElementsByTagName_marker(): NodeListOf<SVGMarkerElement> = jsNative
    // [<Emit("$0.getElementsByTagName('marquee')")>] member __.getElementsByTagName_marquee(): NodeListOf<HTMLMarqueeElement> = jsNative
    // [<Emit("$0.getElementsByTagName('mask')")>] member __.getElementsByTagName_mask(): NodeListOf<SVGMaskElement> = jsNative
    [<Emit("$0.getElementsByTagName('menu')")>] member __.getElementsByTagName_menu(): NodeListOf<HTMLMenuElement> = jsNative
    [<Emit("$0.getElementsByTagName('meta')")>] member __.getElementsByTagName_meta(): NodeListOf<HTMLMetaElement> = jsNative
    // [<Emit("$0.getElementsByTagName('metadata')")>] member __.getElementsByTagName_metadata(): NodeListOf<SVGMetadataElement> = jsNative
    [<Emit("$0.getElementsByTagName('nav')")>] member __.getElementsByTagName_nav(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('nextid')")>] member __.getElementsByTagName_nextid(): NodeListOf<HTMLNextIdElement> = jsNative
    [<Emit("$0.getElementsByTagName('nobr')")>] member __.getElementsByTagName_nobr(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('noframes')")>] member __.getElementsByTagName_noframes(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('noscript')")>] member __.getElementsByTagName_noscript(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('object')")>] member __.getElementsByTagName_object(): NodeListOf<HTMLObjectElement> = jsNative
    [<Emit("$0.getElementsByTagName('ol')")>] member __.getElementsByTagName_ol(): NodeListOf<HTMLOListElement> = jsNative
    [<Emit("$0.getElementsByTagName('optgroup')")>] member __.getElementsByTagName_optgroup(): NodeListOf<HTMLOptGroupElement> = jsNative
    [<Emit("$0.getElementsByTagName('option')")>] member __.getElementsByTagName_option(): NodeListOf<HTMLOptionElement> = jsNative
    [<Emit("$0.getElementsByTagName('p')")>] member __.getElementsByTagName_p(): NodeListOf<HTMLParagraphElement> = jsNative
    [<Emit("$0.getElementsByTagName('param')")>] member __.getElementsByTagName_param(): NodeListOf<HTMLParamElement> = jsNative
    // [<Emit("$0.getElementsByTagName('path')")>] member __.getElementsByTagName_path(): NodeListOf<SVGPathElement> = jsNative
    // [<Emit("$0.getElementsByTagName('pattern')")>] member __.getElementsByTagName_pattern(): NodeListOf<SVGPatternElement> = jsNative
    [<Emit("$0.getElementsByTagName('plaintext')")>] member __.getElementsByTagName_plaintext(): NodeListOf<HTMLBlockElement> = jsNative
    // [<Emit("$0.getElementsByTagName('polygon')")>] member __.getElementsByTagName_polygon(): NodeListOf<SVGPolygonElement> = jsNative
    // [<Emit("$0.getElementsByTagName('polyline')")>] member __.getElementsByTagName_polyline(): NodeListOf<SVGPolylineElement> = jsNative
    [<Emit("$0.getElementsByTagName('pre')")>] member __.getElementsByTagName_pre(): NodeListOf<HTMLPreElement> = jsNative
    [<Emit("$0.getElementsByTagName('progress')")>] member __.getElementsByTagName_progress(): NodeListOf<HTMLProgressElement> = jsNative
    [<Emit("$0.getElementsByTagName('q')")>] member __.getElementsByTagName_q(): NodeListOf<HTMLQuoteElement> = jsNative
    // [<Emit("$0.getElementsByTagName('radialgradient')")>] member __.getElementsByTagName_radialgradient(): NodeListOf<SVGRadialGradientElement> = jsNative
    // [<Emit("$0.getElementsByTagName('rect')")>] member __.getElementsByTagName_rect(): NodeListOf<SVGRectElement> = jsNative
    [<Emit("$0.getElementsByTagName('rt')")>] member __.getElementsByTagName_rt(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('ruby')")>] member __.getElementsByTagName_ruby(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('s')")>] member __.getElementsByTagName_s(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('samp')")>] member __.getElementsByTagName_samp(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('script')")>] member __.getElementsByTagName_script(): NodeListOf<HTMLScriptElement> = jsNative
    [<Emit("$0.getElementsByTagName('section')")>] member __.getElementsByTagName_section(): NodeListOf<HTMLElement> = jsNative
    [<Emit("$0.getElementsByTagName('select')")>] member __.getElementsByTagName_select(): NodeListOf<HTMLSelectElement> = jsNative
    [<Emit("$0.getElementsByTagName('small')")>] member __.getElementsByTagName_small(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('source')")>] member __.getElementsByTagName_source(): NodeListOf<HTMLSourceElement> = jsNative
    [<Emit("$0.getElementsByTagName('span')")>] member __.getElementsByTagName_span(): NodeListOf<HTMLSpanElement> = jsNative
    // [<Emit("$0.getElementsByTagName('stop')")>] member __.getElementsByTagName_stop(): NodeListOf<SVGStopElement> = jsNative
    [<Emit("$0.getElementsByTagName('strike')")>] member __.getElementsByTagName_strike(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('strong')")>] member __.getElementsByTagName_strong(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('style')")>] member __.getElementsByTagName_style(): NodeListOf<HTMLStyleElement> = jsNative
    [<Emit("$0.getElementsByTagName('sub')")>] member __.getElementsByTagName_sub(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('sup')")>] member __.getElementsByTagName_sup(): NodeListOf<HTMLPhraseElement> = jsNative
    // [<Emit("$0.getElementsByTagName('svg')")>] member __.getElementsByTagName_svg(): NodeListOf<SVGSVGElement> = jsNative
    // [<Emit("$0.getElementsByTagName('switch')")>] member __.getElementsByTagName_switch(): NodeListOf<SVGSwitchElement> = jsNative
    // [<Emit("$0.getElementsByTagName('symbol')")>] member __.getElementsByTagName_symbol(): NodeListOf<SVGSymbolElement> = jsNative
    [<Emit("$0.getElementsByTagName('table')")>] member __.getElementsByTagName_table(): NodeListOf<HTMLTableElement> = jsNative
    [<Emit("$0.getElementsByTagName('tbody')")>] member __.getElementsByTagName_tbody(): NodeListOf<HTMLTableSectionElement> = jsNative
    [<Emit("$0.getElementsByTagName('td')")>] member __.getElementsByTagName_td(): NodeListOf<HTMLTableDataCellElement> = jsNative
    // [<Emit("$0.getElementsByTagName('text')")>] member __.getElementsByTagName_text(): NodeListOf<SVGTextElement> = jsNative
    // [<Emit("$0.getElementsByTagName('textpath')")>] member __.getElementsByTagName_textpath(): NodeListOf<SVGTextPathElement> = jsNative
    [<Emit("$0.getElementsByTagName('textarea')")>] member __.getElementsByTagName_textarea(): NodeListOf<HTMLTextAreaElement> = jsNative
    [<Emit("$0.getElementsByTagName('tfoot')")>] member __.getElementsByTagName_tfoot(): NodeListOf<HTMLTableSectionElement> = jsNative
    [<Emit("$0.getElementsByTagName('th')")>] member __.getElementsByTagName_th(): NodeListOf<HTMLTableHeaderCellElement> = jsNative
    [<Emit("$0.getElementsByTagName('thead')")>] member __.getElementsByTagName_thead(): NodeListOf<HTMLTableSectionElement> = jsNative
    [<Emit("$0.getElementsByTagName('title')")>] member __.getElementsByTagName_title(): NodeListOf<HTMLTitleElement> = jsNative
    [<Emit("$0.getElementsByTagName('tr')")>] member __.getElementsByTagName_tr(): NodeListOf<HTMLTableRowElement> = jsNative
    [<Emit("$0.getElementsByTagName('track')")>] member __.getElementsByTagName_track(): NodeListOf<HTMLTrackElement> = jsNative
    // [<Emit("$0.getElementsByTagName('tspan')")>] member __.getElementsByTagName_tspan(): NodeListOf<SVGTSpanElement> = jsNative
    [<Emit("$0.getElementsByTagName('tt')")>] member __.getElementsByTagName_tt(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('u')")>] member __.getElementsByTagName_u(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('ul')")>] member __.getElementsByTagName_ul(): NodeListOf<HTMLUListElement> = jsNative
    // [<Emit("$0.getElementsByTagName('use')")>] member __.getElementsByTagName_use(): NodeListOf<SVGUseElement> = jsNative
    [<Emit("$0.getElementsByTagName('var')")>] member __.getElementsByTagName_var(): NodeListOf<HTMLPhraseElement> = jsNative
    [<Emit("$0.getElementsByTagName('video')")>] member __.getElementsByTagName_video(): NodeListOf<HTMLVideoElement> = jsNative
    // [<Emit("$0.getElementsByTagName('view')")>] member __.getElementsByTagName_view(): NodeListOf<SVGViewElement> = jsNative
    [<Emit("$0.getElementsByTagName('wbr')")>] member __.getElementsByTagName_wbr(): NodeListOf<HTMLElement> = jsNative
    // [<Emit("$0.getElementsByTagName('x-ms-webview')")>] member __.``(): ``: unit -> NodeListOf<MSHTMLWebViewElement> = jsNative
    [<Emit("$0.getElementsByTagName('xmp')")>] member __.getElementsByTagName_xmp(): NodeListOf<HTMLBlockElement> = jsNative
